name: 'Build AppImage'
description: 'Build an AppImage using appimage-builder'
branding:
  icon: 'package'
  color: 'green'
inputs:
  recipe:
    description: 'appimage-builder recipe file'
    required: true
    default: 'AppImageBuilder.yml'
  args:
    description: 'appimage-builder arguments as comma-separated list'
    required: false
    default: '--skip-tests'
runs:
  using: 'docker'
  image: docker://appimagecrafters/appimage-builder:1.1.0
  args: ${{ fromJson(format('["appimage-builder", "--recipe={0}", {1}]', github.event.inputs.recipe, github.event.inputs.args)) }}
