name: 'Build AppImage'
description: 'Build an AppImage using appimage-builder'
branding:
  icon: 'package'
  color: 'green'
inputs:
  recipe:
    description: 'appimage-builder recipe file'
    required: true
    default: 'AppImageBuilder.yml'
  args:
    description: 'appimage-builder arguments as comma-separated list'
    required: false
    default: '--skip-tests'
runs:
  using: composite
  steps:
    - id: transform
      shell: bash
      run: |
        jq -Rncr '"args=" + ([inputs] | tostring | @sh)' >>"${GITHUB_OUTPUT}" <<EOF
        appimage-builder
        --recipe=${{inputs.recipe}}
        ${{inputs.args}}
        EOF
    - uses: docker://appimagecrafters/appimage-builder:1.1.0
      with:
        args: ${{ fromJson(steps.transform.output.args) }}
